# Generated by Django 5.2.5 on 2025-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paplib', '0002_climbrecord_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='写真'),
        ),
    ]
