# Generated by Django 5.2.5 on 2025-08-25 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='山名')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('elevation', models.IntegerField(verbose_name='標高')),
            ],
        ),
        migrations.CreateModel(
            name='ClimbRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb_date', models.DateField(verbose_name='登った日')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='感想・コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paplib.mountain', verbose_name='山')),
            ],
        ),
    ]
