# Generated by Django 5.2.5 on 2025-08-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paplib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
